NAME		= PmergeMe

CXX			= c++
CXXFLAGS	= -Wall -Wextra -Werror -std=c++11 -MMD -MP

SRCDIR		= src
OBJDIR		= obj

SOURCES		= $(SRCDIR)/main.cpp \
			  $(SRCDIR)/PmergeMe.cpp

OBJECTS		= $(addprefix $(OBJDIR)/, $(notdir $(SOURCES:.cpp=.o)))
DEPS		= $(OBJECTS:.o=.d)

GREEN		= \033[0;32m
RED			= \033[0;31m
YELLOW		= \033[0;33m
NC			= \033[0m

all: $(NAME)

$(NAME): $(OBJECTS)
	@$(CXX) $(CXXFLAGS) $(OBJECTS) -o $(NAME)
	@echo "\033[0;92m* $(NAME) program file was created *\033[0m"

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	@mkdir -p $(OBJDIR)
	@printf "* compiling $< *\r"
	@$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	@printf "$(RED)Removing object files...$(NC)\n"
	@rm -rf $(OBJDIR)

fclean: clean
	@printf "$(RED)Removing $(NAME)...$(NC)\n"
	@rm -f $(NAME)

re: fclean all

# Declare phony targets
.PHONY: all clean fclean re

-include $(DEPS)
